apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-auth
data:
  mongo_hostname: {{ .Values.mongo_hostname | b64enc }}
  mongo_db: {{ .Values.mongo_db | b64enc }}
  mongo_user: {{ .Values.mongo_user | b64enc }}
  mongo_pass: {{ .Values.mongo_pass | b64enc }}
