---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app1
  namespace: default
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app1
  replicas: 1 
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app1
    spec:
      containers:
      - image: {{ .Values.image }}
        name: app1
        command: ["node"]
        args: ["/service1/index.js"]
        env:
          - name: MONGO_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-auth
                key: mongo_hostname
          - name: MONGO_DB
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-auth
                key: mongo_db
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-auth
                key: mongo_user
          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-auth
                key: mongo_pass
          - name: MONGODB_URL
            value: mongodb://$(MONGO_USER):$(MONGO_PASS)@$(MONGO_HOSTNAME):27017/$(MONGO_DB)
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service1
  namespace: default
spec:
  ports:
  - port: 3000
    protocol: TCP
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-app1

